version: 2
services:
  0S1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=e548516b68adb5fc52d327e360397fb681f634d7@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
  0S2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=2dda64689cfa361014b97bb0e76cd2ee753a4015@0S1:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
services:
  1S1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 1S1
    hostname: 1S1
    tty: true
    volumes:
    - /home/centos/NFS500/network/1S1/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=1
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=91c1c74c303dd7c62e5aa0829da00138f6f08be1@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S1
  1S2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 1S2
    hostname: 1S2
    tty: true
    volumes:
    - /home/centos/NFS500/network/1S2/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=26796b2fc867bab60a25b3d62461bc2119f05543@1S1:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S2
    links:
    - 1S1

networks:
  tendermintnet1:
    driver: host
