version: 2
services:
  0S1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /root/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=8c85ad409b7001d3fb5b9c9a4f711e0d405121a2@0S5:26656,d02a654b54c70686389e9b6a971b439d8998b898@0S3:26656,0eeb6b3dae3e46db55c828020495c2c092899155@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /root/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=4d823edc7f0dc78883f2992ce661d872b76d8908@0S1:26656,9ce73754ee8e62536bffa654ec11513b53d83b5b@0S4:26656,b68f3365f4e61602eaaa2ee8d9c25d0ce1a4c920@0S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S3
    hostname: 0S3
    tty: true
    volumes:
    - /root/NFS500/network/0S3/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=3
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=4d823edc7f0dc78883f2992ce661d872b76d8908@0S1:26656,7daff37ff07a8e32653b78fc930b9f38f2976905@0S7:26656,9ce73754ee8e62536bffa654ec11513b53d83b5b@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S3
    links:
    - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S4
    hostname: 0S4
    tty: true
    volumes:
    - /root/NFS500/network/0S4/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=4
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=d02a654b54c70686389e9b6a971b439d8998b898@0S3:26656,0eeb6b3dae3e46db55c828020495c2c092899155@0S2:26656,9359f51fab2fec581dda5113d37f081126899f06@0S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S4
    links:
    - 0S3
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S5:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S5
    hostname: 0S5
    tty: true
    volumes:
    - /root/NFS500/network/0S5/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=5
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=4d823edc7f0dc78883f2992ce661d872b76d8908@0S1:26656,7daff37ff07a8e32653b78fc930b9f38f2976905@0S7:26656,b68f3365f4e61602eaaa2ee8d9c25d0ce1a4c920@0S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S5
    links:
    - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S6:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S6
    hostname: 0S6
    tty: true
    volumes:
    - /root/NFS500/network/0S6/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=6
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=8c85ad409b7001d3fb5b9c9a4f711e0d405121a2@0S5:26656,9359f51fab2fec581dda5113d37f081126899f06@0S8:26656,0eeb6b3dae3e46db55c828020495c2c092899155@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S6
    links:
    - 0S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S7:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S7
    hostname: 0S7
    tty: true
    volumes:
    - /root/NFS500/network/0S7/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=7
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=8c85ad409b7001d3fb5b9c9a4f711e0d405121a2@0S5:26656,d02a654b54c70686389e9b6a971b439d8998b898@0S3:26656,9359f51fab2fec581dda5113d37f081126899f06@0S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S7
    links:
    - 0S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S8:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S8
    hostname: 0S8
    tty: true
    volumes:
    - /root/NFS500/network/0S8/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=8
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=9ce73754ee8e62536bffa654ec11513b53d83b5b@0S4:26656,b68f3365f4e61602eaaa2ee8d9c25d0ce1a4c920@0S6:26656,7daff37ff07a8e32653b78fc930b9f38f2976905@0S7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S8
    links:
    - 0S4
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
services:
  1S1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S1
    hostname: 1S1
    tty: true
    volumes:
    - /root/NFS500/network/1S1/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=1
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=492d3555185cbad89d5aad622481aa1b239d1bab@1S5:26656,4dbbb2c3cac1edaa8133f6f47e505cad88a5425b@1S3:26656,0dc56f400dd6fb60b2dfbed4be7104a92909aa33@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S2
    hostname: 1S2
    tty: true
    volumes:
    - /root/NFS500/network/1S2/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=2
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=bce6f3dd261370db14bb42eaf1f8a48588274187@1S1:26656,90ee6519cfa53c9139500a104ae1630e3b28e684@1S4:26656,e75e088dcac3d0ed4c38615d6a36c2b3657cc2d3@1S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S2
    links:
    - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S3
    hostname: 1S3
    tty: true
    volumes:
    - /root/NFS500/network/1S3/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=3
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=bce6f3dd261370db14bb42eaf1f8a48588274187@1S1:26656,4c0adc8f4c642409da97f815a8cd82dd36bc23b1@1S7:26656,90ee6519cfa53c9139500a104ae1630e3b28e684@1S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S3
    links:
    - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S4
    hostname: 1S4
    tty: true
    volumes:
    - /root/NFS500/network/1S4/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=4
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=4dbbb2c3cac1edaa8133f6f47e505cad88a5425b@1S3:26656,0dc56f400dd6fb60b2dfbed4be7104a92909aa33@1S2:26656,0644e15c6ddbd347205c7f238fd835eb74d9412c@1S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S4
    links:
    - 1S3
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S5:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S5
    hostname: 1S5
    tty: true
    volumes:
    - /root/NFS500/network/1S5/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=5
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=bce6f3dd261370db14bb42eaf1f8a48588274187@1S1:26656,4c0adc8f4c642409da97f815a8cd82dd36bc23b1@1S7:26656,e75e088dcac3d0ed4c38615d6a36c2b3657cc2d3@1S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S5
    links:
    - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S6:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S6
    hostname: 1S6
    tty: true
    volumes:
    - /root/NFS500/network/1S6/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=6
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=492d3555185cbad89d5aad622481aa1b239d1bab@1S5:26656,0644e15c6ddbd347205c7f238fd835eb74d9412c@1S8:26656,0dc56f400dd6fb60b2dfbed4be7104a92909aa33@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S6
    links:
    - 1S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S7:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S7
    hostname: 1S7
    tty: true
    volumes:
    - /root/NFS500/network/1S7/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=7
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=492d3555185cbad89d5aad622481aa1b239d1bab@1S5:26656,4dbbb2c3cac1edaa8133f6f47e505cad88a5425b@1S3:26656,0644e15c6ddbd347205c7f238fd835eb74d9412c@1S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S7
    links:
    - 1S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S8:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S8
    hostname: 1S8
    tty: true
    volumes:
    - /root/NFS500/network/1S8/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=8
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=90ee6519cfa53c9139500a104ae1630e3b28e684@1S4:26656,e75e088dcac3d0ed4c38615d6a36c2b3657cc2d3@1S6:26656,4c0adc8f4c642409da97f815a8cd82dd36bc23b1@1S7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S8
    links:
    - 1S4
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin

networks:
  tendermintnet1:
    driver: host
