version: 2
services:
  0S1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=547b2a2d488eb06a43f1850a734727e58472bbe0@0S3:26656,0d19733332fa3e98965ea164c079156560dbb4fc@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
  0S2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=355fe833cea03ff155bb2c7a4f6db70cc96c46f6@0S1:26656,d62139c0e442c9e30d5e792181ccada6cd92e693@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
  0S3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S3
    hostname: 0S3
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S3/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=3
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=355fe833cea03ff155bb2c7a4f6db70cc96c46f6@0S1:26656,d62139c0e442c9e30d5e792181ccada6cd92e693@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S3
    links:
    - 0S1
  0S4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S4
    hostname: 0S4
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S4/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=4
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=547b2a2d488eb06a43f1850a734727e58472bbe0@0S3:26656,0d19733332fa3e98965ea164c079156560dbb4fc@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S4
    links:
    - 0S3
services:
  1S1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 1S1
    hostname: 1S1
    tty: true
    volumes:
    - /home/centos/NFS500/network/1S1/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=1
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=1f1aca3706d43112486c6cc903a67178a3038fd3@1S3:26656,abd79134489cf70b392b37dccf3923a3574a07a9@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S1
  1S2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 1S2
    hostname: 1S2
    tty: true
    volumes:
    - /home/centos/NFS500/network/1S2/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=2
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=6fd137a56e33d95424f5146905f16d57eda367e1@1S1:26656,1cf7aa86b8df310b01772241e10e8e898583d85f@1S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S2
    links:
    - 1S1
  1S3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 1S3
    hostname: 1S3
    tty: true
    volumes:
    - /home/centos/NFS500/network/1S3/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=3
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=6fd137a56e33d95424f5146905f16d57eda367e1@1S1:26656,1cf7aa86b8df310b01772241e10e8e898583d85f@1S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S3
    links:
    - 1S1
  1S4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 1S4
    hostname: 1S4
    tty: true
    volumes:
    - /home/centos/NFS500/network/1S4/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=4
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=1f1aca3706d43112486c6cc903a67178a3038fd3@1S3:26656,abd79134489cf70b392b37dccf3923a3574a07a9@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S4
    links:
    - 1S3

networks:
  tendermintnet1:
    driver: host
