version: 2
services:
  0S1:
    image: tendermint:latest
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /root/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=471289320ee599658f0dd26c280c479f12fe63dc@0S3:26656,32fcdd4f8e60d6f9616b47570fca8c4efb0934ab@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
  0S2:
    image: tendermint:latest
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /root/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=6b137cbeda5d24f526b9250c22736e6130285118@0S1:26656,4ad371dc391a4af677fb7a525259cfdf380cbe0c@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
  0S3:
    image: tendermint:latest
    container_name: 0S3
    hostname: 0S3
    tty: true
    volumes:
    - /root/NFS500/network/0S3/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=3
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=6b137cbeda5d24f526b9250c22736e6130285118@0S1:26656,4ad371dc391a4af677fb7a525259cfdf380cbe0c@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S3
    links:
    - 0S1
  0S4:
    image: tendermint:latest
    container_name: 0S4
    hostname: 0S4
    tty: true
    volumes:
    - /root/NFS500/network/0S4/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=4
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=471289320ee599658f0dd26c280c479f12fe63dc@0S3:26656,32fcdd4f8e60d6f9616b47570fca8c4efb0934ab@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S4
    links:
    - 0S3

networks:
  tendermintnet1:
    driver: host
