version: 2
services:
  TTANode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTANode1
    hostname: TTANode1
    tty: true
    volumes: ['/home/centos/NFS500/network/TTANode1/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=475b74f965fb76cb68ba7ff80bb04e93c7a20379@TTANode3:26656,96b23a9057a9c4d523b4d520e494146524c70762@TTANode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTANode1]
  TTANode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTANode2
    hostname: TTANode2
    tty: true
    volumes: ['/home/centos/NFS500/network/TTANode2/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=bed6d5e2102c4fa03b026a5486a1e31c809a88a1@TTANode1:26656,f4027fe4206b4f2c71ab02d9db2e7cf1bcfc6908@TTANode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTANode2]
  TTANode3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTANode3
    hostname: TTANode3
    tty: true
    volumes: ['/home/centos/NFS500/network/TTANode3/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=bed6d5e2102c4fa03b026a5486a1e31c809a88a1@TTANode1:26656,f4027fe4206b4f2c71ab02d9db2e7cf1bcfc6908@TTANode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTANode3]
  TTANode4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTANode4
    hostname: TTANode4
    tty: true
    volumes: ['/home/centos/NFS500/network/TTANode4/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=475b74f965fb76cb68ba7ff80bb04e93c7a20379@TTANode3:26656,96b23a9057a9c4d523b4d520e494146524c70762@TTANode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTANode4]
services:
  TTBNode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTBNode1
    hostname: TTBNode1
    tty: true
    volumes: ['/home/centos/NFS500/network/TTBNode1/config:/tendermint/config']
    environment: [TASKID=B]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=7db04e5f10bcbebea7e95c5d11c09dcc4d69aa40@TTBNode3:26656,8c4eaee3d76eaa90e816f6dcbdd8b229d937edff@TTBNode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTBNode1]
  TTBNode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTBNode2
    hostname: TTBNode2
    tty: true
    volumes: ['/home/centos/NFS500/network/TTBNode2/config:/tendermint/config']
    environment: [TASKID=B]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=0a4d35a04c44ec286bd042cccc0142f7e7fccf5d@TTBNode1:26656,224cfa56f6da5291a8df5082df5120b8811782d4@TTBNode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTBNode2]
  TTBNode3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTBNode3
    hostname: TTBNode3
    tty: true
    volumes: ['/home/centos/NFS500/network/TTBNode3/config:/tendermint/config']
    environment: [TASKID=B]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=0a4d35a04c44ec286bd042cccc0142f7e7fccf5d@TTBNode1:26656,224cfa56f6da5291a8df5082df5120b8811782d4@TTBNode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTBNode3]
  TTBNode4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTBNode4
    hostname: TTBNode4
    tty: true
    volumes: ['/home/centos/NFS500/network/TTBNode4/config:/tendermint/config']
    environment: [TASKID=B]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=7db04e5f10bcbebea7e95c5d11c09dcc4d69aa40@TTBNode3:26656,8c4eaee3d76eaa90e816f6dcbdd8b229d937edff@TTBNode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [TTBNode4]

networks:
  tendermintnet1:
    driver: host
