version: 2
services:
  0S1:
    image: tendermint:latest
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /root/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=4c74565e61937df454b28bf4660d85e448c669ce@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
  0S2:
    image: tendermint:latest
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /root/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=6d085e1070c039a3d90b5f426ba4a999cf1b0543@0S1:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
services:
  1S1:
    image: tendermint:latest
    container_name: 1S1
    hostname: 1S1
    tty: true
    volumes:
    - /root/NFS500/network/1S1/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=1
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=6ecf3fbd76f88aa2b77d8df9b918eb1b85108f13@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S1
  1S2:
    image: tendermint:latest
    container_name: 1S2
    hostname: 1S2
    tty: true
    volumes:
    - /root/NFS500/network/1S2/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=bad5a7f2d795756cb4b133f4fbcb6afb50f28cc7@1S1:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S2
    links:
    - 1S1

networks:
  tendermintnet1:
    driver: host
