version: '2'
services:
  0S1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S1
    hostname: 0S1
    tty: true
    ports:
      - 26657:26657
    volumes:
    - /home/centos/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=b6be889a254b54f524f7b3c5cb3b499de663307a@0S3:26656,3909666c3fa54fcc3445b031967e8c330cac88a9@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
  0S2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=76b734c88bad0c8bcefe1dbcc4993dbb91b5ba1b@0S1:26656,78e8ae116bb5baac55269cd8e6b05e79951386c4@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
  0S3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S3
    hostname: 0S3
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S3/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=3
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=76b734c88bad0c8bcefe1dbcc4993dbb91b5ba1b@0S1:26656,78e8ae116bb5baac55269cd8e6b05e79951386c4@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
  0S4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: 0S4
    hostname: 0S4
    tty: true
    volumes:
    - /home/centos/NFS500/network/0S4/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=4
    - THRESHOLD=2
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=b6be889a254b54f524f7b3c5cb3b499de663307a@0S3:26656,3909666c3fa54fcc3445b031967e8c330cac88a9@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore

