version: 2
services:
  0S1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /root/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=3d5a752f63f79804f850c85b37e025753372766d@0S5:26656,34e147f38bc2334da41a825254dd24c9df08624a@0S3:26656,089eadb6173dd80afc2fef48c1bfa5a2849be155@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /root/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=b8d7107ee450bfcf6e7f177b34b95fcd4ea65cbd@0S1:26656,fb74a4a833ec31c3eb0d2ac634793bc05bc4d5a5@0S4:26656,e0e6f5e9d2997aff18d535747a387efe98e31b76@0S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S3
    hostname: 0S3
    tty: true
    volumes:
    - /root/NFS500/network/0S3/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=3
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=b8d7107ee450bfcf6e7f177b34b95fcd4ea65cbd@0S1:26656,eaa2b3747faaf7bd7c5c0c50be8b72164f3bbce5@0S7:26656,fb74a4a833ec31c3eb0d2ac634793bc05bc4d5a5@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S3
    links:
    - 0S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S4
    hostname: 0S4
    tty: true
    volumes:
    - /root/NFS500/network/0S4/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=4
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=34e147f38bc2334da41a825254dd24c9df08624a@0S3:26656,089eadb6173dd80afc2fef48c1bfa5a2849be155@0S2:26656,44172354b4308f3317b8185d4d5ceaa5d5d41aef@0S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S4
    links:
    - 0S3
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S5:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S5
    hostname: 0S5
    tty: true
    volumes:
    - /root/NFS500/network/0S5/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=5
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=b8d7107ee450bfcf6e7f177b34b95fcd4ea65cbd@0S1:26656,eaa2b3747faaf7bd7c5c0c50be8b72164f3bbce5@0S7:26656,e0e6f5e9d2997aff18d535747a387efe98e31b76@0S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S5
    links:
    - 0S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S6:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S6
    hostname: 0S6
    tty: true
    volumes:
    - /root/NFS500/network/0S6/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=6
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=3d5a752f63f79804f850c85b37e025753372766d@0S5:26656,44172354b4308f3317b8185d4d5ceaa5d5d41aef@0S8:26656,089eadb6173dd80afc2fef48c1bfa5a2849be155@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S6
    links:
    - 0S5
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S7:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S7
    hostname: 0S7
    tty: true
    volumes:
    - /root/NFS500/network/0S7/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=7
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=3d5a752f63f79804f850c85b37e025753372766d@0S5:26656,34e147f38bc2334da41a825254dd24c9df08624a@0S3:26656,44172354b4308f3317b8185d4d5ceaa5d5d41aef@0S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S7
    links:
    - 0S5
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
  0S8:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S8
    hostname: 0S8
    tty: true
    volumes:
    - /root/NFS500/network/0S8/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=8
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=fb74a4a833ec31c3eb0d2ac634793bc05bc4d5a5@0S4:26656,e0e6f5e9d2997aff18d535747a387efe98e31b76@0S6:26656,eaa2b3747faaf7bd7c5c0c50be8b72164f3bbce5@0S7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S8
    links:
    - 0S4
    labels:
      io.rancher.scheduler.affinity:host_label: label=1
services:
  1S1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S1
    hostname: 1S1
    tty: true
    volumes:
    - /root/NFS500/network/1S1/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=1
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=789e0ae3953c22c6554057674dfeae5d173b019f@1S5:26656,898dac3cf1e7af96ca84ac305e2d01e88e5c818b@1S3:26656,583df859eee2e8d0b4904c31a98694bf52fd89e1@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S2
    hostname: 1S2
    tty: true
    volumes:
    - /root/NFS500/network/1S2/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=2
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=9e8fe56cb9cddb360ca4b124b7923db898caf6f6@1S1:26656,32e3909fa0cd782c109809430586e826fa54ad23@1S4:26656,9a1124989a3a60b6700c2f168cbb27e92d81bc1f@1S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S2
    links:
    - 1S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S3
    hostname: 1S3
    tty: true
    volumes:
    - /root/NFS500/network/1S3/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=3
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=9e8fe56cb9cddb360ca4b124b7923db898caf6f6@1S1:26656,c65ea2f895b5a59b59785db0e12ab5125e3d55ab@1S7:26656,32e3909fa0cd782c109809430586e826fa54ad23@1S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S3
    links:
    - 1S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S4
    hostname: 1S4
    tty: true
    volumes:
    - /root/NFS500/network/1S4/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=4
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=898dac3cf1e7af96ca84ac305e2d01e88e5c818b@1S3:26656,583df859eee2e8d0b4904c31a98694bf52fd89e1@1S2:26656,509dec7a48f5cc3b58a34df0c719ac4d054a9e5f@1S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S4
    links:
    - 1S3
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S5:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S5
    hostname: 1S5
    tty: true
    volumes:
    - /root/NFS500/network/1S5/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=5
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=9e8fe56cb9cddb360ca4b124b7923db898caf6f6@1S1:26656,c65ea2f895b5a59b59785db0e12ab5125e3d55ab@1S7:26656,9a1124989a3a60b6700c2f168cbb27e92d81bc1f@1S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S5
    links:
    - 1S1
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S6:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S6
    hostname: 1S6
    tty: true
    volumes:
    - /root/NFS500/network/1S6/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=6
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=789e0ae3953c22c6554057674dfeae5d173b019f@1S5:26656,509dec7a48f5cc3b58a34df0c719ac4d054a9e5f@1S8:26656,583df859eee2e8d0b4904c31a98694bf52fd89e1@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S6
    links:
    - 1S5
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S7:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S7
    hostname: 1S7
    tty: true
    volumes:
    - /root/NFS500/network/1S7/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=7
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=789e0ae3953c22c6554057674dfeae5d173b019f@1S5:26656,898dac3cf1e7af96ca84ac305e2d01e88e5c818b@1S3:26656,509dec7a48f5cc3b58a34df0c719ac4d054a9e5f@1S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S7
    links:
    - 1S5
    labels:
      io.rancher.scheduler.affinity:host_label: label=2
  1S8:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S8
    hostname: 1S8
    tty: true
    volumes:
    - /root/NFS500/network/1S8/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=8
    - THRESHOLD=6
    - Count=8
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=32e3909fa0cd782c109809430586e826fa54ad23@1S4:26656,9a1124989a3a60b6700c2f168cbb27e92d81bc1f@1S6:26656,c65ea2f895b5a59b59785db0e12ab5125e3d55ab@1S7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S8
    links:
    - 1S4
    labels:
      io.rancher.scheduler.affinity:host_label: label=2

networks:
  tendermintnet1:
    driver: host
