version: 2
services:
  0S1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S1
    hostname: 0S1
    tty: true
    volumes:
    - /root/NFS500/network/0S1/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=1
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=dd7f97c8507ba2a53bef0f405b9fcd16c5bb9b5c@0S5:26656,5e4df16a797dadea8815ca4955be4b1001b70196@0S3:26656,0d3db18ffb55630e6fd9e18a03d9249fb7497d34@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S2
    hostname: 0S2
    tty: true
    volumes:
    - /root/NFS500/network/0S2/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=2
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=84ab53eb4e222c3d360e9627bae0f1a43e6c5e03@0S1:26656,5c73d5e86ae5275faecc6895277dd8992a357832@0S4:26656,bae37b167952261bda94c7b32f55449135b0b9ff@0S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S2
    links:
    - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S3
    hostname: 0S3
    tty: true
    volumes:
    - /root/NFS500/network/0S3/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=3
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=84ab53eb4e222c3d360e9627bae0f1a43e6c5e03@0S1:26656,497ff2729ef16288bfef7af59b1ae5af6c5ddb24@0S7:26656,5c73d5e86ae5275faecc6895277dd8992a357832@0S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S3
    links:
    - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S4
    hostname: 0S4
    tty: true
    volumes:
    - /root/NFS500/network/0S4/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=4
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=5e4df16a797dadea8815ca4955be4b1001b70196@0S3:26656,0d3db18ffb55630e6fd9e18a03d9249fb7497d34@0S2:26656,35777e28a527d495bf09ffb90a0a33b2c5b4b892@0S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S4
    links:
    - 0S3
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S5:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S5
    hostname: 0S5
    tty: true
    volumes:
    - /root/NFS500/network/0S5/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=5
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=84ab53eb4e222c3d360e9627bae0f1a43e6c5e03@0S1:26656,497ff2729ef16288bfef7af59b1ae5af6c5ddb24@0S7:26656,bae37b167952261bda94c7b32f55449135b0b9ff@0S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S5
    links:
    - 0S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S6:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S6
    hostname: 0S6
    tty: true
    volumes:
    - /root/NFS500/network/0S6/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=6
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=dd7f97c8507ba2a53bef0f405b9fcd16c5bb9b5c@0S5:26656,35777e28a527d495bf09ffb90a0a33b2c5b4b892@0S8:26656,0d3db18ffb55630e6fd9e18a03d9249fb7497d34@0S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S6
    links:
    - 0S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S7:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S7
    hostname: 0S7
    tty: true
    volumes:
    - /root/NFS500/network/0S7/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=7
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=dd7f97c8507ba2a53bef0f405b9fcd16c5bb9b5c@0S5:26656,5e4df16a797dadea8815ca4955be4b1001b70196@0S3:26656,35777e28a527d495bf09ffb90a0a33b2c5b4b892@0S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S7
    links:
    - 0S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  0S8:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 0S8
    hostname: 0S8
    tty: true
    volumes:
    - /root/NFS500/network/0S8/config:/tendermint/config
    environment:
    - TASKID=0
    - TASKINDEX=8
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=5c73d5e86ae5275faecc6895277dd8992a357832@0S4:26656,bae37b167952261bda94c7b32f55449135b0b9ff@0S6:26656,497ff2729ef16288bfef7af59b1ae5af6c5ddb24@0S7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 0S8
    links:
    - 0S4
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
services:
  1S1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S1
    hostname: 1S1
    tty: true
    volumes:
    - /root/NFS500/network/1S1/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=1
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=21c57192b11b9cc0f59b05b58ec1eea3e7fb02bd@1S5:26656,dea1aebab608ece0c1d0655958500c223fced701@1S3:26656,99fe41c25493bba82c82ad5e7f20dcb3eccae5b4@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S2
    hostname: 1S2
    tty: true
    volumes:
    - /root/NFS500/network/1S2/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=2
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=1c2bebfdc493373d80057301aab91cee7df8d679@1S1:26656,64172ae98fdeaf124d2833f2a7362a2b26461c4a@1S4:26656,51929dfff098be8796b9db815345b2ec7fb7003f@1S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S2
    links:
    - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S3
    hostname: 1S3
    tty: true
    volumes:
    - /root/NFS500/network/1S3/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=3
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=1c2bebfdc493373d80057301aab91cee7df8d679@1S1:26656,61b34d56455fcd0cc128c975cd07b0cdfe97a379@1S7:26656,64172ae98fdeaf124d2833f2a7362a2b26461c4a@1S4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S3
    links:
    - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S4
    hostname: 1S4
    tty: true
    volumes:
    - /root/NFS500/network/1S4/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=4
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=dea1aebab608ece0c1d0655958500c223fced701@1S3:26656,99fe41c25493bba82c82ad5e7f20dcb3eccae5b4@1S2:26656,165c8ca542178e3fcf76b73d0993f6a00eb0e894@1S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S4
    links:
    - 1S3
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S5:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S5
    hostname: 1S5
    tty: true
    volumes:
    - /root/NFS500/network/1S5/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=5
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=1c2bebfdc493373d80057301aab91cee7df8d679@1S1:26656,61b34d56455fcd0cc128c975cd07b0cdfe97a379@1S7:26656,51929dfff098be8796b9db815345b2ec7fb7003f@1S6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S5
    links:
    - 1S1
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S6:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S6
    hostname: 1S6
    tty: true
    volumes:
    - /root/NFS500/network/1S6/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=6
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=21c57192b11b9cc0f59b05b58ec1eea3e7fb02bd@1S5:26656,165c8ca542178e3fcf76b73d0993f6a00eb0e894@1S8:26656,99fe41c25493bba82c82ad5e7f20dcb3eccae5b4@1S2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S6
    links:
    - 1S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S7:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S7
    hostname: 1S7
    tty: true
    volumes:
    - /root/NFS500/network/1S7/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=7
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=21c57192b11b9cc0f59b05b58ec1eea3e7fb02bd@1S5:26656,dea1aebab608ece0c1d0655958500c223fced701@1S3:26656,165c8ca542178e3fcf76b73d0993f6a00eb0e894@1S8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S7
    links:
    - 1S5
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin
  1S8:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/shardingbc:latest
    container_name: 1S8
    hostname: 1S8
    tty: true
    volumes:
    - /root/NFS500/network/1S8/config:/tendermint/config
    environment:
    - TASKID=1
    - TASKINDEX=8
    - THRESHOLD=6
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=64172ae98fdeaf124d2833f2a7362a2b26461c4a@1S4:26656,51929dfff098be8796b9db815345b2ec7fb7003f@1S6:26656,61b34d56455fcd0cc128c975cd07b0cdfe97a379@1S7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - 1S8
    links:
    - 1S4
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.0.190:24224
        tag: docker.origin

networks:
  tendermintnet1:
    driver: host
